In [1]:
# this is my first titanic dataset workout,
#there are two datasets , train dataset and test dataset

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df_train=pd.read_csv("train.csv")
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df_test=pd.read_csv("test.csv")
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [6]:
print(df_train.shape)
print(df_test.shape)

(891, 12)
(418, 11)


In [7]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

#since cabin column has maximum no. of nul values and
#also it affects least on our targeted variable it is better to drop the column... 

In [9]:
df_train.drop(columns="Cabin",axis=1,inplace=True)

In [10]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [11]:
df_train.Age.fillna(value=df_train.Age.mean(),inplace=True)

In [12]:
df_train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [14]:
df_train.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [15]:
df_train[df_train.Embarked=='S'].count()

PassengerId    644
Survived       644
Pclass         644
Name           644
Sex            644
Age            644
SibSp          644
Parch          644
Ticket         644
Fare           644
Embarked       644
dtype: int64

In [16]:
df_train[df_train.Embarked=='C'].count()

PassengerId    168
Survived       168
Pclass         168
Name           168
Sex            168
Age            168
SibSp          168
Parch          168
Ticket         168
Fare           168
Embarked       168
dtype: int64

In [17]:
df_train[df_train.Embarked=='C'].count()

PassengerId    168
Survived       168
Pclass         168
Name           168
Sex            168
Age            168
SibSp          168
Parch          168
Ticket         168
Fare           168
Embarked       168
dtype: int64

In [18]:
#since 'S' is the maximum times filled as the values , so fill nan values with the 'S' as value.

In [19]:
df_train.loc[df_train.Embarked=='S']

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
..           ...       ...     ...   
883          884         0       2   
884          885         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   

                                             Name     Sex        Age  SibSp  \
0                         Braund, Mr. Owen Harris    male  22.000000      1   
2                          Heikkinen, Miss. Laina  female  26.000000      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000      1   
4                        Allen, Mr. William Henry    male  35.000000      0   
6                         McCarthy, Mr. Timothy J    male  54.000000      0   
..                                            ...     ...        ...    ...   
883                 Banfield, Mr. Frederick James    male  28.000000      0   
884                        Sutehall, Mr. Henry Jr    male  25.000000      0   
886                         Montvila, Rev. Juozas    male  27.000000      0   
887                  Graham, Miss. Margaret Edith  female  19.000000      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female  29.699118      1   

     Parch            Ticket     Fare Embarked  
0        0         A/5 21171   7.2500        S  
2        0  STON/O2. 3101282   7.9250        S  
3        0            113803  53.1000        S  
4        0            373450   8.0500        S  
6        0             17463  51.8625        S  
..     ...               ...      ...      ...  
883      0  C.A./SOTON 34068  10.5000        S  
884      0   SOTON/OQ 392076   7.0500        S  
886      0            211536  13.0000        S  
887      0            112053  30.0000        S  
888      2        W./C. 6607  23.4500        S  

[644 rows x 11 columns]

In [21]:
df_train.loc[df_train.Embarked.isna()].Embarked

61     NaN
829    NaN
Name: Embarked, dtype: object

In [22]:
df_train.Embarked.fillna(value='S',inplace=True)

In [23]:
df_train.loc[df_train.Embarked.isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked]
Index: []

In [24]:
df_train.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

#now the data is clean and has no null values

In [25]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [26]:
filtered_df_train=df_train[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Embarked']]

In [27]:
filtered_df_train.set_index('PassengerId',inplace=True)

In [28]:
filtered_df_train.head()

Pclass     Sex   Age  SibSp  Parch Embarked
PassengerId                                             
1                 3    male  22.0      1      0        S
2                 1  female  38.0      1      0        C
3                 3  female  26.0      0      0        S
4                 1  female  35.0      1      0        S
5                 3    male  35.0      0      0        S

In [29]:
y_df_train=df_train['Survived']

In [30]:
y_df_train.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [31]:
filtered_df_train.Pclass.unique()

array([3, 1, 2], dtype=int64)

In [32]:
filtered_df_train.Sex.unique()

array(['male', 'female'], dtype=object)

In [33]:
filtered_df_train.SibSp.unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [34]:
filtered_df_train.Parch.unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [36]:
filtered_df_train.Sex.replace({'male':1,'female':2},inplace=True)
filtered_df_train.head()

C:\Users\Dell\Anaconda3\lib\site-packages\pandas\core\generic.py:6786: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


Pclass  Sex   Age  SibSp  Parch Embarked
PassengerId                                          
1                 3    1  22.0      1      0        S
2                 1    2  38.0      1      0        C
3                 3    2  26.0      0      0        S
4                 1    2  35.0      1      0        S
5                 3    1  35.0      0      0        S

In [37]:
filtered_df_train.Embarked.unique()

array(['S', 'C', 'Q'], dtype=object)

In [38]:
filtered_df_train.Embarked.replace({'S':0,'C':1,'Q':2}, inplace=True)
filtered_df_train.head()

Pclass  Sex   Age  SibSp  Parch  Embarked
PassengerId                                           
1                 3    1  22.0      1      0         0
2                 1    2  38.0      1      0         1
3                 3    2  26.0      0      0         0
4                 1    2  35.0      1      0         0
5                 3    1  35.0      0      0         0

In [40]:
filtered_df_train.plot.box()

In [41]:
min=filtered_df_train.Age.min()
max=filtered_df_train.Age.max()
print(min ," ", max)

0.42   80.0


In [42]:
filtered_df_train.Age=(filtered_df_train.Age-min)/(max-min)

C:\Users\Dell\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [43]:
filtered_df_train.head()

Pclass  Sex       Age  SibSp  Parch  Embarked
PassengerId                                               
1                 3    1  0.271174      1      0         0
2                 1    2  0.472229      1      0         1
3                 3    2  0.321438      0      0         0
4                 1    2  0.434531      1      0         0
5                 3    1  0.434531      0      0         0

In [44]:
df_x=np.array(filtered_df_train)
df_x

array([[3.        , 1.        , 0.27117366, 1.        , 0.        ,
        0.        ],
       [1.        , 2.        , 0.4722292 , 1.        , 0.        ,
        1.        ],
       [3.        , 2.        , 0.32143755, 0.        , 0.        ,
        0.        ],
       ...,
       [3.        , 2.        , 0.36792055, 1.        , 2.        ,
        0.        ],
       [1.        , 1.        , 0.32143755, 0.        , 0.        ,
        1.        ],
       [3.        , 1.        , 0.39683338, 0.        , 0.        ,
        2.        ]])

In [46]:
df_y=np.array(y_df_train)
df_y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [53]:
#model= DecisionTreeClassifier()
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=10,max_leaf_nodes=10,random_state=0)

In [54]:
model.fit(df_x,df_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=10,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [55]:
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [56]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [57]:
filtered_df_test=df_test[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Embarked']]
filtered_df_test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch Embarked
0          892       3    male  34.5      0      0        Q
1          893       3  female  47.0      1      0        S
2          894       2    male  62.0      0      0        Q
3          895       3    male  27.0      0      0        S
4          896       3  female  22.0      1      1        S

In [58]:
filtered_df_test.set_index('PassengerId',inplace=True)

In [60]:
filtered_df_test.Age.fillna(value=filtered_df_test.Age.mean(),inplace=True)

C:\Users\Dell\Anaconda3\lib\site-packages\pandas\core\generic.py:6287: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [61]:
filtered_df_test.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [63]:
filtered_df_test.head()

Pclass     Sex   Age  SibSp  Parch Embarked
PassengerId                                             
892               3    male  34.5      0      0        Q
893               3  female  47.0      1      0        S
894               2    male  62.0      0      0        Q
895               3    male  27.0      0      0        S
896               3  female  22.0      1      1        S

In [62]:
test_min=filtered_df_test.Age.min()
test_max=filtered_df_test.Age.max()
print(max," ",min)

80.0   0.42


In [64]:
filtered_df_test.Age=(filtered_df_test.Age-test_min)/(test_max-test_min)
filtered_df_test.head()

C:\Users\Dell\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


Pclass     Sex       Age  SibSp  Parch Embarked
PassengerId                                                 
892               3    male  0.452723      0      0        Q
893               3  female  0.617566      1      0        S
894               2    male  0.815377      0      0        Q
895               3    male  0.353818      0      0        S
896               3  female  0.287881      1      1        S

In [65]:
filtered_df_test.Sex.replace({'male':1,'female':0},inplace=True)
filtered_df_test.Embarked.replace({'S':0,'C':1,'Q':2},inplace=True)
filtered_df_test.head()

C:\Users\Dell\Anaconda3\lib\site-packages\pandas\core\generic.py:6786: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


Pclass  Sex       Age  SibSp  Parch  Embarked
PassengerId                                               
892               3    1  0.452723      0      0         2
893               3    0  0.617566      1      0         0
894               2    1  0.815377      0      0         2
895               3    1  0.353818      0      0         0
896               3    0  0.287881      1      1         0

In [66]:
Y_pred=model.predict(filtered_df_test)

In [67]:
predicted_y=pd.DataFrame({'PassengerId':filtered_df_test.index,'Survived':Y_pred})

In [74]:
predicted_y.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0